version: "3.9"
services:
  dev:
    image: spark:3.5.4-scala2.12-java17-python3-ubuntu
    hostname: dev-container
    volumes:
      - ..:/workspace
    command: tail -f /dev/null
    user: root
    networks:
      - spark-network
  
  spark-master:
    image: spark:3.5.4-scala2.12-java17-python3-ubuntu
    container_name: spark-master
    command: ["/bin/bash", "-c", "wget -P /opt/spark/jars https://jdbc.postgresql.org/download/postgresql-42.2.23.jar && /opt/spark/sbin/start-master.sh && tail -f /dev/null"]
    environment:
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - spark-network

  spark-worker-1:
    image: spark:3.5.4-scala2.12-java17-python3-ubuntu
    container_name: spark-worker-1
    command: ["/bin/bash", "-c", "wget -P /opt/spark/jars https://jdbc.postgresql.org/download/postgresql-42.2.23.jar && /opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"]
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
    ports:
      - "8081:8080"
    depends_on:
      - spark-master
    networks:
      - spark-network
  
  spark-worker-2:
    image: spark:3.5.4-scala2.12-java17-python3-ubuntu
    container_name: spark-worker-2
    command: ["/bin/bash", "-c", "wget -P /opt/spark/jars https://jdbc.postgresql.org/download/postgresql-42.2.23.jar && /opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"]
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
    ports:
      - "8082:8080"
    depends_on:
      - spark-master
    networks:
      - spark-network
  
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    shm_size: '1gb'
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - spark-network

networks:
  spark-network: 
    driver: bridge